CREATE TABLE `cdi2_self` (
  `CommentID` varchar(255) NOT NULL DEFAULT '',
  `UserID` varchar(255) DEFAULT NULL,
  `Examiner` varchar(255) DEFAULT NULL,
  `Testdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL DEFAULT 'Incomplete',
  `Date_taken` date DEFAULT NULL,
  `Candidate_Age` varchar(255) DEFAULT NULL,
  `Window_Difference` int(11) DEFAULT NULL,
  `cdi_item_1` enum('0', '1', '2', 'not_answered') DEFAULT NULL,
  `cdi_item_2` enum('2', '1', '0', 'not_answered') DEFAULT NULL,
  `cdi_item_3` enum('0', '1', '2', 'not_answered') DEFAULT NULL,
  `cdi_item_4` enum('0', '1', '2', 'not_answered') DEFAULT NULL,
  `cdi_item_5` enum('0', '1', '2', 'not_answered') DEFAULT NULL,
  `cdi_item_6` enum('2', '1', '0', 'not_answered') DEFAULT NULL,
  `cdi_item_7` enum('2', '1', '0', 'not_answered') DEFAULT NULL,
  `cdi_item_8` enum('2', '1', '0', 'not_answered') DEFAULT NULL,
  `cdi_item_9` enum('2', '1', '0', 'not_answered') DEFAULT NULL,
  `cdi_item_10` enum('0', '1', '2', 'not_answered') DEFAULT NULL,
  `cdi_item_11` enum('2', '1', '0', 'not_answered') DEFAULT NULL,
  `cdi_item_12` enum('0', '1', '2', 'not_answered') DEFAULT NULL,
  `cdi_total_raw` tinyint DEFAULT NULL,
  `cdi_t_score` tinyint DEFAULT NULL,
  PRIMARY KEY (`CommentID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
