CREATE TABLE `conners3_teacher` (
  `CommentID` varchar(255) NOT NULL DEFAULT '',
  `UserID` varchar(255) DEFAULT NULL,
  `Examiner` varchar(255) DEFAULT NULL,
  `Testdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL DEFAULT 'Incomplete',
  `Date_taken` date DEFAULT NULL,
  `Candidate_Age` varchar(255) DEFAULT NULL,
  `Window_Difference` int(11) DEFAULT NULL,
  `q001` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q002` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q003` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q004` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q005` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q006` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q007` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q008` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q009` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q010` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q011` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q012` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q013` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q014` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q015` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q016` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q017` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q018` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q019` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q020` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q021` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q022` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q023` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q024` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q025` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q026` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q027` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q028` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q029` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q030` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q031` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q032` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q033` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q034` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q035` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q036` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q037` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q038` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q039` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q040` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q041` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q042` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q043` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q044` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q045` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q046` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q047` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q048` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q049` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q050` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q051` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q052` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q053` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q054` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q055` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q056` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q057` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q058` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q059` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q060` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q061` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q062` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q063` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q064` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q065` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q066` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q067` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q068` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q069` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q070` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q071` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q072` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q073` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q074` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q075` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q076` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q077` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q078` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q079` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q080` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q081` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q082` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q083` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q084` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q085` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q086` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q087` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q088` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q089` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q090` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q091` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q092` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q093` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q094` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q095` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q096` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q097` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q098` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q099` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q100` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q101` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q102` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q103` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q104` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q105` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q106` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q107` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q108` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q109` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q110` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q111` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q112` text,
  `q112_status` enum('not_answered') DEFAULT NULL,
  `q113` text,
  `q113_status` enum('not_answered') DEFAULT NULL,
  `raw_in` smallint,
  `raw_hy` smallint,
  `raw_le` smallint,
  `raw_lp` smallint,
  `raw_ef` smallint,
  `raw_ag` smallint,
  `raw_pr` smallint,
  `raw_gi` smallint,
  `raw_an` smallint,
  `raw_ah` smallint,
  `raw_cd` smallint,
  `raw_od` smallint,
  `raw_pi` smallint,
  `raw_ni` smallint,
  `inconsistency` tinyint,
  `pi` tinyint,
  `ni` tinyint,
  `adhd_inattentive_a1a` tinyint,
  `adhd_inattentive_a1b` tinyint,
  `adhd_inattentive_a1c` tinyint,
  `adhd_inattentive_a1d` tinyint,
  `adhd_inattentive_a1e` tinyint,
  `adhd_inattentive_a1f` tinyint,
  `adhd_inattentive_a1g` tinyint,
  `adhd_inattentive_a1h` tinyint,
  `adhd_inattentive_a1i` tinyint,
  `adhd_inattentive` tinyint,
  `adhd_hyp_imp_a2a` tinyint,
  `adhd_hyp_imp_a2b` tinyint,
  `adhd_hyp_imp_a2c` tinyint,
  `adhd_hyp_imp_a2d` tinyint,
  `adhd_hyp_imp_a2e` tinyint,
  `adhd_hyp_imp_a2f` tinyint,
  `adhd_hyp_imp_a2g` tinyint,
  `adhd_hyp_imp_a2h` tinyint,
  `adhd_hyp_imp_a2i` tinyint,
  `adhd_hyp_imp` tinyint,
  `cond_dis_a1` tinyint,
  `cond_dis_a2` tinyint,
  `cond_dis_a3` tinyint,
  `cond_dis_a4` tinyint,
  `cond_dis_a5` tinyint,
  `cond_dis_a6` tinyint,
  `cond_dis_a7` tinyint,
  `cond_dis_a8` tinyint,
  `cond_dis_a9` tinyint,
  `cond_dis_a10` tinyint,
  `cond_dis_a11` tinyint,
  `cond_dis_a12` tinyint,
  `cond_dis_a13` tinyint,
  `cond_dis_a14` tinyint,
  `cond_dis_a15` tinyint,
  `cond_dis` tinyint,
  `op_def_a1` tinyint,
  `op_def_a2` tinyint,
  `op_def_a3` tinyint,
  `op_def_a4` tinyint,
  `op_def_a5` tinyint,
  `op_def_a6` tinyint,
  `op_def_a7` tinyint,
  `op_def_a8` tinyint,
  `op_def` tinyint,
  `adhd_index_transposed` tinyint,
  `adhd_index_probability` tinyint,
  PRIMARY KEY (`CommentID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO test_names (Test_name, Full_name, Sub_group) VALUES ('conners3_teacher','Connners 3 Teacher',1);
INSERT INTO instrument_subtests (`Test_name`, `Subtest_name`, `Description`, `Order_number`) VALUES ('conners3_teacher', 'conners3_teacher_page1', 'Items', '1');