CREATE TABLE `srs2_schoolage` (
  `CommentID` varchar(255) NOT NULL DEFAULT '',
  `srs_school_age_1` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_2` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_3` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_4` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_5` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_6` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_7` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_8` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_9` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_10` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_11` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_12` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_13` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_14` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_15` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_16` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_17` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_18` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_19` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_20` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_21` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_22` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_23` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_24` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_25` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_26` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_27` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_28` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_29` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_30` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_31` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_32` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_33` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_34` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_35` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_36` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_37` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_38` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_39` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_40` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_41` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_42` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_43` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_44` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_45` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_46` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_47` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_48` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_49` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_50` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_51` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_52` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_53` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_54` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_55` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_56` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_57` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_58` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_59` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_60` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_61` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_62` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_63` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_64` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_65` enum('1','2','3','4','not_answered') DEFAULT NULL,
  `srs_school_age_awr` tinyint unsigned DEFAULT NULL,
  `srs_school_age_cog` tinyint unsigned DEFAULT NULL,
  `srs_school_age_com` tinyint unsigned DEFAULT NULL,
  `srs_school_age_mot` tinyint unsigned DEFAULT NULL,
  `srs_school_age_rrb` tinyint unsigned DEFAULT NULL,
  `srs_school_age_awr_t` tinyint unsigned DEFAULT NULL,
  `srs_school_age_cog_t` tinyint unsigned DEFAULT NULL,
  `srs_school_age_com_t` tinyint unsigned DEFAULT NULL,
  `srs_school_age_mot_t` tinyint unsigned DEFAULT NULL,
  `srs_school_age_rrb_t` tinyint unsigned DEFAULT NULL,
  `srs_school_age_sci` tinyint unsigned DEFAULT NULL,
  `srs_school_age_sci_t` tinyint unsigned DEFAULT NULL,
  `srs_school_age_total` tinyint unsigned DEFAULT NULL,
  `srs_school_age_total_t` tinyint unsigned DEFAULT NULL,
  `UserID` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`CommentID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
