CREATE TABLE `adhd_rs_home` (
  `CommentID` varchar(255) NOT NULL DEFAULT '',
  `UserID` varchar(255) DEFAULT NULL,
  `Examiner` varchar(255) DEFAULT NULL,
  `Testdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL DEFAULT 'Incomplete',
  `Date_taken` date DEFAULT NULL,
  `Candidate_Age` varchar(255) DEFAULT NULL,
  `Window_Difference` int(11) DEFAULT NULL,
  `q01` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q02` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q03` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q04` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q05` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q06` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q07` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q08` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q09` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q10` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q11` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q12` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q13` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q14` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q15` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q16` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q17` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q18` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q19` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q20` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q21` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q22` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q23` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q24` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q25` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q26` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q27` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q28` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q29` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `q30` enum('0', '1', '2', '3', 'not_answered') DEFAULT NULL,
  `inatt_raw` tinyint,
  `inatt_sx` tinyint,
  `inatt_tscore` tinyint,
  `hyp_raw` tinyint,
  `hyp_sx` tinyint,
  `hyp_tscore` tinyint,
  PRIMARY KEY (`CommentID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
