CREATE TABLE `psi` (
    `CommentID` varchar(255) NOT NULL DEFAULT '',
    `UserID` varchar(255) DEFAULT NULL,
    `psi_1` enum("","1","0"),
    `psi_2` enum("","1","0"),
    `psi_3` enum("","1","0"),
    `psi_4` enum("","1","0"),
    `psi_5` enum("","1","0"),
    `psi_6` enum("","1","0"),
    `psi_7` enum("","1","0"),
    `psi_8` enum("","1","0"),
    `psi_9` enum("","1","0"),
    `psi_10` enum("","1","0"),
    `psi_11` enum("","1","0"),
    `psi_12` enum("","1","0"),
    `psi_13` enum("","1","0"),
    `psi_14` enum("","1","0"),
    `psi_15` enum("","1","0"),
    `psi_16` enum("","1","0"),
    `psi_17` enum("","1","0"),
    `psi_18` enum("","1","0"),
    `psi_19` enum("","1","0"),
    `psi_20` enum("","1","0"),
    PRIMARY KEY (`CommentID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8