CREATE TABLE `rbsr` (
    `CommentID` varchar(255) NOT NULL DEFAULT '',
    `UserID` varchar(255) DEFAULT NULL,
    `repetitive_behavior_scale_` enum("","1","2"),
    `repetitive_behavior_scale_1` enum("","0","1","2","3"),
    `repetitive_behavior_scale_2` enum("","0","1","2","3"),
    `repetitive_behavior_scale_3` enum("","0","1","2","3"),
    `repetitive_behavior_scale_4` enum("","0","1","2","3"),
    `repetitive_behavior_scale_5` enum("","0","1","2","3"),
    `repetitive_behavior_scale_6` enum("","0","1","2","3"),
    `repetitive_behavior_scale_7` enum("","0","1","2","3"),
    `repetitive_behavior_scale_8` enum("","0","1","2","3"),
    `repetitive_behavior_scale_9` enum("","0","1","2","3"),
    `repetitive_behavior_scale_10` enum("","0","1","2","3"),
    `repetitive_behavior_scale_11` enum("","0","1","2","3"),
    `repetitive_behavior_scale_12` enum("","0","1","2","3"),
    `repetitive_behavior_scale_13` enum("","0","1","2","3"),
    `repetitive_behavior_scale_14` enum("","0","1","2","3"),
    `repetitive_behavior_scale_15` enum("","0","1","2","3"),
    `repetitive_behavior_scale_16` enum("","0","1","2","3"),
    `repetitive_behavior_scale_17` enum("","0","1","2","3"),
    `repetitive_behavior_scale_18` enum("","0","1","2","3"),
    `repetitive_behavior_scale_19` enum("","0","1","2","3"),
    `repetitive_behavior_scale_20` enum("","0","1","2","3"),
    `repetitive_behavior_scale_21` enum("","0","1","2","3"),
    `repetitive_behavior_scale_22` enum("","0","1","2","3"),
    `repetitive_behavior_scale_23` enum("","0","1","2","3"),
    `repetitive_behavior_scale_24` enum("","0","1","2","3"),
    `repetitive_behavior_scale_25` enum("","0","1","2","3"),
    `repetitive_behavior_scale_26` enum("","0","1","2","3"),
    `repetitive_behavior_scale_27` enum("","0","1","2","3"),
    `repetitive_behavior_scale_28` enum("","0","1","2","3"),
    `repetitive_behavior_scale_29` enum("","0","1","2","3"),
    `repetitive_behavior_scale_30` enum("","0","1","2","3"),
    `repetitive_behavior_scale_31` enum("","0","1","2","3"),
    `repetitive_behavior_scale_32` enum("","0","1","2","3"),
    `repetitive_behavior_scale_33` enum("","0","1","2","3"),
    `repetitive_behavior_scale_34` enum("","0","1","2","3"),
    `repetitive_behavior_scale_35` enum("","0","1","2","3"),
    `repetitive_behavior_scale_36` enum("","0","1","2","3"),
    `repetitive_behavior_scale_37` enum("","0","1","2","3"),
    `repetitive_behavior_scale_38` enum("","0","1","2","3"),
    `repetitive_behavior_scale_39` enum("","0","1","2","3"),
    `repetitive_behavior_scale_40` enum("","0","1","2","3"),
    `repetitive_behavior_scale_41` enum("","0","1","2","3"),
    `repetitive_behavior_scale_42` enum("","0","1","2","3"),
    `repetitive_behavior_scale_43` enum("","0","1","2","3"),
    PRIMARY KEY (`CommentID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8